version: '2'
services:
  web:
    image: nginx:1.11-alpine
    container_name: api.whalesale.com
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./inf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
  app:
    image: 1maa/php-fpm:7.0-xdebug
    ports:
      - "2222:22"
    volumes:
      - .:/var/www/api.whalesale.com
    working_dir: /var/www/api.whalesale.com
