security:
    providers:
        customer_provider:
            id: sec.customer_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|homepage)|css|images|js)/
            security: false
        hmac_api:
            stateless: true
            simple_preauth:
                authenticator: uma.hmac_auth
            provider: customer_provider
