security:
    providers:
        customer_provider:
            entity:
                class: AppBundle\Entity\Customer
                property: apiKey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|homepage)|css|images|js)/
            security: false
        hmac_api:
            hmac: true
            provider: customer_provider
            stateless: true
