services:
    json.bad_req_listener:
        class: AppBundle\EventListener\BadJsonRequestExceptionListener
        tags:
            - { name: kernel.event_subscriber }
    json.req_listener:
        class: AppBundle\EventListener\JsonRequestListener
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_subscriber }

    json.uri_retriever:
        class: JsonSchema\Uri\UriRetriever
        public: false
    json.uri_resolver:
        class: JsonSchema\Uri\UriResolver
        public: false
    json.ref_resolver:
        class: JsonSchema\RefResolver
        public: false
        arguments:
            - '@json.uri_retriever'
            - '@json.uri_resolver'

    schemas.update_shipping_address:
        class: \stdClass
        factory: ['@json.ref_resolver', 'resolve']
        arguments:
            - '%schema_path%/update_shipping_address.json'
    schemas.place_product_order:
        class: \stdClass
        factory: ['@json.ref_resolver', 'resolve']
        arguments:
            - '%schema_path%/place_product_order.json'
