imports:
    - { resource: commands.yml }
    - { resource: normalizers.yml }
    - { resource: repositories.yml }
    - { resource: schemas.yml }
    - { resource: use_cases.yml }

services:
    sec.verifier:
        class: UMA\Psr7Hmac\Verifier
        public: false
    sec.customer_provider:
        class: AppBundle\Security\CustomerProvider
        arguments:
            - '@repo.customer'
    sec.hmac_auth:
        class: AppBundle\Security\Psr7HmacAuthenticator
        arguments:
            - 'Api-Key'
            - '@sec.verifier'
