services:
    cmd.manage_customers:
        class: AppBundle\Command\ManageCustomersCommand
        arguments:
            - '@use_case.create_customer'
            - '@repo.customer'
        tags:
            - { name: console.command }
    cmd.api.update_shipping_address:
            class: AppBundle\Command\Api\UpdateShippingAddressCommand
            arguments:
                - '@repo.customer'
            tags:
                - { name: console.command }

    repo.customer:
        class: AppBundle\Repository\CustomerRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'AppBundle:Customer'
    repo.product_order:
        class: AppBundle\Repository\ProductOrderRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'AppBundle:ProductOrder'

    subs.bad_json_req:
        class: AppBundle\EventListener\BadJsonRequestExceptionListener
        tags:
            - { name: kernel.event_subscriber }
    subs.json_req:
        class: AppBundle\EventListener\JsonRequestListener
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_subscriber }

    use_case.create_customer:
        class: AppBundle\UseCase\CreateCustomerUseCase
        arguments:
            - '@doctrine.orm.default_entity_manager'
    use_case.place_order:
        class: AppBundle\UseCase\PlaceOrderUseCase
        arguments:
            - '@doctrine.orm.default_entity_manager'
    use_case.update_shipping_address:
        class: AppBundle\UseCase\UpdateShippingAddressUseCase
        arguments:
            - '@doctrine.orm.default_entity_manager'

    json.uri_retriever:
        class: JsonSchema\Uri\UriRetriever
        public: false
    json.uri_resolver:
        class: JsonSchema\Uri\UriResolver
        public: false
    json.ref_resolver:
        class: JsonSchema\RefResolver
        public: false
        arguments:
            - '@json.uri_retriever'
            - '@json.uri_resolver'
    json_schema.update_shipping_address:
        class: \stdClass
        factory: ['@json.ref_resolver', 'resolve']
        arguments:
            - '%schema_path%/update_shipping_address.json'
    json_schema.place_product_order:
        class: \stdClass
        factory: ['@json.ref_resolver', 'resolve']
        arguments:
            - '%schema_path%/place_product_order.json'

    sec.verifier:
        class: UMA\Psr7Hmac\Verifier
        public: false
    sec.customer_provider:
        class: AppBundle\Security\CustomerProvider
        arguments:
            - '@repo.customer'
    sec.hmac_auth:
        class: AppBundle\Security\Psr7HmacAuthenticator
        arguments:
            - 'Api-Key'
            - '@sec.verifier'
