services:
    use_case.create_customer:
        class: AppBundle\UseCase\CreateCustomerUseCase
        arguments:
            - '@doctrine.orm.default_entity_manager'
    use_case.place_order:
        class: AppBundle\UseCase\PlaceOrderUseCase
        arguments:
            - '@doctrine.orm.default_entity_manager'
    use_case.update_shipping_address:
        class: AppBundle\UseCase\UpdateShippingAddressUseCase
        arguments:
            - '@doctrine.orm.default_entity_manager'
